name: build-and-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: read   # solo necesitamos leer paquetes para restore

env:
  PROJECT_PATH: src/UNIR.TFE.Polyrepo.Subtraction.Module/UNIR.TFE.Polyrepo.Subtraction.Module.csproj
  TEST_PATH: test/UNIR.TFE.Polyrepo.Subtraction.Module.Test/UNIR.TFE.Polyrepo.Subtraction.Module.Test.csproj

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Fuente NuGet de GitHub (idempotente)
      - name: Configure GitHub Packages source
        shell: bash
        run: |
          SRC_NAME="github-ajunquit"
          SRC_URL="https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          if dotnet nuget list source | grep -q "$SRC_NAME"; then
            dotnet nuget update source "$SRC_NAME" \
              --username ${{ github.actor }} \
              --password ${{ secrets.GITHUB_TOKEN }} \
              --store-password-in-clear-text \
              --source "$SRC_URL"
          else
            dotnet nuget add source "$SRC_URL" \
              --name "$SRC_NAME" \
              --username ${{ github.actor }} \
              --password ${{ secrets.GITHUB_TOKEN }} \
              --store-password-in-clear-text
          fi
          dotnet nuget list source

      - name: Auth for GitHub Packages
        run: echo "NUGET_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Restore
        run: |
          dotnet restore $PROJECT_PATH
          dotnet restore $TEST_PATH

      - name: Build
        run: dotnet build $PROJECT_PATH -c Release --no-restore

      - name: Test (unit tests + coverage)
        run: |
          dotnet test $TEST_PATH -c Release \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory ./test-results \
            --collect:"XPlat Code Coverage"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ./test-results
            **/TestResults/**/*.trx
            **/TestResults/**/*.xml
